name: 'ProductNow Action'
description: 'Says Hello world!'
inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  mcp_url:
    description: 'MCP server URL'
    required: true
  interval_hours:
    description: 'Interval, in hours, between runs'
    required: false
    default: '3'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: echo "Hello world!"
